import { Router } from "express";
import { authRouter } from "./auth.routes";
import { companyRouter } from "./company.routes";
import { jobRouter } from "./jobs.routes";
import { skillRouter } from "./skills.routes";
import { jobSkillRouter } from "./job-skills.routes";
const router = Router();
router.use("/companies", companyRouter);
router.use("/auth", authRouter);
router.use("/jobs", jobRouter);
router.use("/skills", skillRouter);
router.use("/jobs", jobSkillRouter);
export default router;