"use strict";

/**
 * Human-authored source material for the demo dataset.
 *
 * IDs, timestamps, relationships, and stage paths are deliberately generated
 * elsewhere. Keeping the prose and role catalog here makes it possible to
 * review the quality of the demo data without reading seeding mechanics.
 */

const COMPANIES = [
  {
    key: "northwind",
    name: "Northwind Labs",
    industry: "Developer Tools",
    size: "201-500 employees",
    location: "London, United Kingdom (remote-first)",
    contact: "talent@northwindlabs.example.com",
    website: "https://northwindlabs.example.com",
    description:
      "Northwind Labs builds observability and workflow tools for product engineering teams operating data-intensive systems.",
    logoFile: "northwind-labs.svg",
    subscriptionTier: "PRO",
    staff: [
      {
        name: "Maya Chen",
        email: "recruiter@northwindlabs.example.com",
        role: "RECRUITER",
      },
      {
        name: "Omar Haddad",
        email: "interviewer@northwindlabs.example.com",
        role: "INTERVIEWER",
      },
      {
        name: "Elena Rossi",
        email: "recruiter2@northwindlabs.example.com",
        role: "RECRUITER",
      },
    ],
  },
  {
    key: "cedar",
    name: "Cedar Health Systems",
    industry: "Healthcare Technology",
    size: "51-200 employees",
    location: "Beirut, Lebanon",
    contact: "people@cedarhealth.example.com",
    website: "https://cedarhealth.example.com",
    description:
      "Cedar Health Systems gives clinics a secure operating platform for patient coordination, reporting, and clinical data exchange.",
    logoFile: "cedar-health.svg",
    subscriptionTier: "FREE",
    staff: [
      {
        name: "Rami Khoury",
        email: "recruiter@cedarhealth.example.com",
        role: "RECRUITER",
      },
      {
        name: "Talia Brooks",
        email: "interviewer@cedarhealth.example.com",
        role: "INTERVIEWER",
      },
      {
        name: "Jasmine Okafor",
        email: "recruiter2@cedarhealth.example.com",
        role: "RECRUITER",
      },
    ],
  },
  {
    key: "atlaspay",
    name: "AtlasPay",
    industry: "Financial Technology",
    size: "501-1,000 employees",
    location: "Dubai, United Arab Emirates",
    contact: "careers@atlaspay.example.com",
    website: "https://atlaspay.example.com",
    description:
      "AtlasPay provides payment orchestration, fraud tooling, and treasury infrastructure for businesses trading across emerging markets.",
    logoFile: "atlaspay.svg",
    subscriptionTier: "PRO",
    staff: [
      {
        name: "Noor Al-Masri",
        email: "recruiter@atlaspay.example.com",
        role: "RECRUITER",
      },
      {
        name: "Vikram Shah",
        email: "interviewer@atlaspay.example.com",
        role: "INTERVIEWER",
      },
      {
        name: "Sophie Martin",
        email: "recruiter2@atlaspay.example.com",
        role: "RECRUITER",
      },
    ],
  },
  {
    key: "lumen",
    name: "Lumen Commerce",
    industry: "E-commerce",
    size: "51-200 employees",
    location: "Toronto, Canada",
    contact: "join@lumencommerce.example.com",
    website: "https://lumencommerce.example.com",
    description:
      "Lumen Commerce helps independent brands manage storefronts, lifecycle marketing, and marketplace operations from one workspace.",
    logoFile: "lumen-commerce.svg",
    subscriptionTier: "FREE",
    staff: [
      {
        name: "Claire Dubois",
        email: "recruiter@lumencommerce.example.com",
        role: "RECRUITER",
      },
      {
        name: "Marcus Reid",
        email: "interviewer@lumencommerce.example.com",
        role: "INTERVIEWER",
      },
      {
        name: "Amina Diallo",
        email: "recruiter2@lumencommerce.example.com",
        role: "RECRUITER",
      },
    ],
  },
  {
    key: "greenline",
    name: "Greenline Mobility",
    industry: "Clean Transportation",
    size: "501-1,000 employees",
    location: "Berlin, Germany",
    contact: "talent@greenlinemobility.example.com",
    website: "https://greenlinemobility.example.com",
    description:
      "Greenline Mobility operates connected electric fleets and develops the software used to plan routes, monitor batteries, and reduce urban emissions.",
    logoFile: "greenline-mobility.svg",
    subscriptionTier: "PRO",
    staff: [
      {
        name: "Lena Hoffmann",
        email: "recruiter@greenlinemobility.example.com",
        role: "RECRUITER",
      },
      {
        name: "Tomas Oliveira",
        email: "interviewer@greenlinemobility.example.com",
        role: "INTERVIEWER",
      },
      {
        name: "Fatou Ndiaye",
        email: "recruiter2@greenlinemobility.example.com",
        role: "RECRUITER",
      },
    ],
  },
];

// The first ten preserve the IDs/names used by the original small seeder so
// an existing demo database can be upgraded cleanly in place.
const SKILLS = [
  "React",
  "TypeScript",
  "PostgreSQL",
  "Node.js",
  "Docker",
  "GraphQL",
  "AWS",
  "Redis",
  "Python",
  "Kubernetes",
  "JavaScript",
  "Next.js",
  "Go",
  "Terraform",
  "Kafka",
  "SQL",
  "dbt",
  "Snowflake",
  "Airflow",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "Vue",
  "Angular",
  "Figma",
  "Product Strategy",
  "User Research",
  "Cypress",
  "Playwright",
  "Selenium",
  "Swift",
  "Kotlin",
  "React Native",
  "Machine Learning",
  "PyTorch",
  "Data Analysis",
  "Tableau",
  "Fraud Detection",
  "REST",
  "GitHub Actions",
  "Linux",
  "Accessibility",
  "Content Strategy",
  "Customer Success",
  "Clinical Data",
];

const CANDIDATE_NAMES = [
  "Amara Okafor",
  "Lina Haddad",
  "Mateo Alvarez",
  "Priya Raman",
  "Jonas Berg",
  "Yuki Tanaka",
  "Noura El-Sayed",
  "Lucas Moreau",
  "Aisha Khan",
  "Diego Ferreira",
  "Mei Lin",
  "Samira Benali",
  "Ethan Williams",
  "Sofia Petrov",
  "Kwame Mensah",
  "Elena Vasquez",
  "Arjun Mehta",
  "Maya Laurent",
  "Gabriel Silva",
  "Leila Mansour",
  "Noah Thompson",
  "Zara Iqbal",
  "Hugo Laurent",
  "Ananya Iyer",
  "Tariq Rahman",
  "Valentina Costa",
  "Min-jun Park",
  "Iris van Dijk",
  "Omar Farouk",
  "Camila Torres",
  "David Kim",
  "Fatima Zahra",
  "Nikolai Ivanov",
  "Sara Nasser",
  "Rafael Mendes",
  "Chiamaka Eze",
  "Emilia Kowalska",
  "Rohan Gupta",
  "Hana Suzuki",
  "Youssef Khalil",
  "Isabella Romano",
  "Malik Johnson",
  "Ines Duarte",
  "Chen Wei",
  "Mariam Abebe",
  "Theo Martin",
  "Kavya Nair",
  "Adam Nowak",
  "Layla Hussein",
  "Daniel Ortiz",
  "Aya Nakamura",
  "Samuel Adeyemi",
  "Clara Jensen",
  "Reem Saleh",
  "Alejandro Ruiz",
  "Neha Kapoor",
  "Louis Dubois",
  "Salma Bouchard",
  "Joon-ho Lee",
  "Marta Garcia",
  "Ibrahim Diallo",
  "Eva Muller",
  "Zainab Bello",
  "Andrei Popescu",
  "Nur Aisyah",
  "Felipe Rocha",
  "Dalia Karam",
  "Milan Jovanovic",
  "Grace Wanjiku",
  "Benjamin Clark",
  "Rania Hamdan",
  "Thiago Santos",
  "Amina Yusuf",
  "Alex Novak",
  "Saanvi Desai",
  "Victor Nguyen",
  "Lucia Bianchi",
  "Karim Bouaziz",
  "Chloe Bernard",
  "Aditya Rao",
  "Maryam Qureshi",
  "Oscar Lindstrom",
  "Yara Awad",
  "Bruno Almeida",
  "Ji-eun Kim",
  "Nadia Petrova",
  "Ahmed Mansour",
  "Helena Sousa",
  "Kofi Boateng",
  "Tenzin Dolma",
  "Marco Conti",
  "Farah Siddiqui",
  "Sebastian Weber",
  "Nia Campbell",
  "Pablo Herrera",
  "Shreya Kulkarni",
  "Arthur Leblanc",
  "Mona Fadel",
  "Kenji Sato",
  "Bianca Oliveira",
  "Hamza Idrissi",
  "Ana-Maria Stoica",
  "Siti Rahma",
  "George Papadopoulos",
  "Ritu Sharma",
  "Tomasz Zielinski",
  "Wafa Hariri",
  "Andre Santos",
];

const LOCATIONS = [
  ["Lagos, Nigeria", "+234"],
  ["Beirut, Lebanon", "+961"],
  ["Madrid, Spain", "+34"],
  ["Bengaluru, India", "+91"],
  ["Stockholm, Sweden", "+46"],
  ["Tokyo, Japan", "+81"],
  ["Cairo, Egypt", "+20"],
  ["Paris, France", "+33"],
  ["Karachi, Pakistan", "+92"],
  ["Sao Paulo, Brazil", "+55"],
  ["Singapore", "+65"],
  ["Casablanca, Morocco", "+212"],
  ["Austin, United States", "+1"],
  ["Warsaw, Poland", "+48"],
  ["Accra, Ghana", "+233"],
  ["Milan, Italy", "+39"],
  ["Toronto, Canada", "+1"],
  ["Amsterdam, Netherlands", "+31"],
  ["Lisbon, Portugal", "+351"],
  ["Nairobi, Kenya", "+254"],
  ["Berlin, Germany", "+49"],
  ["Dubai, United Arab Emirates", "+971"],
  ["Seoul, South Korea", "+82"],
  ["Melbourne, Australia", "+61"],
];

const EMPLOYERS = [
  "Blue Harbor Software",
  "Juniper Works",
  "Orbitlane",
  "Mosaic Cloud",
  "Harbor & Finch",
  "SignalNest",
  "Kiteframe",
  "Cobalt Systems",
  "Brightwell Digital",
  "Fieldstone Labs",
  "Rivet Analytics",
  "NimbusCart",
  "Redwood Platform Co.",
  "Saffron Health",
  "Meridian Payments",
  "Copperline Studio",
  "Oak & Byte",
  "Tidalworks",
  "Beacon Grid",
  "Paperplane Products",
  "Sundial Data",
  "Clearpath Mobility",
  "Monarch Commerce",
  "Crescent Financial",
  "Vela Networks",
  "Ternary Health",
  "Kindred Market",
  "Northstar Logistics",
  "Daybreak AI",
  "CivicStack",
  "Pinecone Media",
  "Driftwood Security",
  "Evergreen Energy",
  "Lantern Education",
  "Stonebridge Consulting",
  "Willow Research",
];

const INSTITUTIONS = [
  "University of Lagos",
  "American University of Beirut",
  "Universidad Politecnica de Madrid",
  "Indian Institute of Technology Delhi",
  "KTH Royal Institute of Technology",
  "Waseda University",
  "Cairo University",
  "Universite Paris-Saclay",
  "National University of Sciences and Technology",
  "University of Sao Paulo",
  "National University of Singapore",
  "Mohammed V University",
  "University of Texas at Austin",
  "Warsaw University of Technology",
  "University of Ghana",
  "Politecnico di Milano",
  "University of Toronto",
  "Delft University of Technology",
  "University of Lisbon",
  "University of Nairobi",
  "Technical University of Berlin",
  "American University in Dubai",
  "KAIST",
  "University of Melbourne",
];

const ARCHETYPES = [
  {
    headline: "Senior Full-Stack Engineer | React, Node.js, PostgreSQL",
    currentTitle: "Senior Software Engineer",
    priorTitle: "Full-Stack Engineer",
    years: 9,
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "GraphQL", "AWS"],
    summary:
      "I lead full-stack delivery from schema design through accessible interfaces, with a focus on dependable systems and pragmatic mentoring.",
    impact:
      "Led a cross-functional product squad and reduced release lead time while scaling a high-traffic customer workflow.",
    degree: "BSc",
    field: "Computer Science",
  },
  {
    headline: "Frontend Engineer | Design systems and accessibility",
    currentTitle: "Frontend Engineer",
    priorTitle: "UI Engineer",
    years: 5,
    skills: ["React", "TypeScript", "Next.js", "Figma", "Accessibility", "Playwright"],
    summary:
      "I build polished, inclusive product interfaces and the component systems that help teams ship them consistently.",
    impact:
      "Created a shared component library, improved keyboard navigation, and cut common UI defects across three product teams.",
    degree: "BDes",
    field: "Interaction Design",
  },
  {
    headline: "Backend Engineer | Distributed systems and payments",
    currentTitle: "Senior Backend Engineer",
    priorTitle: "Software Engineer",
    years: 8,
    skills: ["Go", "Node.js", "PostgreSQL", "Redis", "Kafka", "Docker"],
    summary:
      "I enjoy high-throughput services, explicit failure modes, and the quiet satisfaction of a well-designed idempotency key.",
    impact:
      "Reworked an event-driven settlement service that doubled throughput and materially reduced duplicate processing incidents.",
    degree: "BEng",
    field: "Software Engineering",
  },
  {
    headline: "Data Engineer | Reliable analytics platforms",
    currentTitle: "Data Engineer",
    priorTitle: "Analytics Engineer",
    years: 6,
    skills: ["Python", "SQL", "dbt", "Snowflake", "Airflow", "AWS"],
    summary:
      "I turn scattered operational data into documented, tested datasets that analysts and product teams can trust.",
    impact:
      "Built incremental pipelines and ownership checks that brought the daily reporting SLA from hours late to consistently on time.",
    degree: "MSc",
    field: "Data Science",
  },
  {
    headline: "Platform Engineer | Kubernetes, Terraform, observability",
    currentTitle: "Platform Engineer",
    priorTitle: "DevOps Engineer",
    years: 7,
    skills: ["Kubernetes", "Terraform", "AWS", "Docker", "Linux", "GitHub Actions"],
    summary:
      "I make the paved road the easy road: reproducible infrastructure, useful telemetry, and deployment tooling teams actually adopt.",
    impact:
      "Standardized deployment templates for dozens of services and reduced recovery time through clearer observability and runbooks.",
    degree: "BSc",
    field: "Information Systems",
  },
  {
    headline: "Product Designer | Complex B2B workflows",
    currentTitle: "Product Designer",
    priorTitle: "UX Designer",
    years: 6,
    skills: ["Figma", "User Research", "Product Strategy", "Accessibility", "Content Strategy"],
    summary:
      "I make complicated operational software feel calm by pairing field research with fast prototyping and close engineering partnership.",
    impact:
      "Redesigned a multi-step onboarding journey that improved completion while establishing reusable patterns for the wider product.",
    degree: "MA",
    field: "Human-Computer Interaction",
  },
  {
    headline: "Technical Product Manager | Platforms and APIs",
    currentTitle: "Product Manager",
    priorTitle: "Business Analyst",
    years: 7,
    skills: ["Product Strategy", "User Research", "SQL", "REST", "Data Analysis"],
    summary:
      "I translate customer problems into focused platform roadmaps and keep product, engineering, and go-to-market teams aligned on outcomes.",
    impact:
      "Launched an API product from discovery to general availability and grew adoption through measurable developer-experience improvements.",
    degree: "MBA",
    field: "Technology Management",
  },
  {
    headline: "QA Automation Engineer | Fast, trustworthy releases",
    currentTitle: "QA Automation Engineer",
    priorTitle: "Software Test Engineer",
    years: 5,
    skills: ["Cypress", "Playwright", "Selenium", "TypeScript", "GitHub Actions", "REST"],
    summary:
      "I design risk-based test strategies and automation that gives teams confidence without turning the pipeline into a bottleneck.",
    impact:
      "Introduced contract and browser test suites that caught regressions earlier and reduced manual release verification substantially.",
    degree: "BSc",
    field: "Computer Engineering",
  },
  {
    headline: "Mobile Engineer | Native-quality cross-platform apps",
    currentTitle: "Mobile Engineer",
    priorTitle: "iOS Developer",
    years: 6,
    skills: ["React Native", "TypeScript", "Swift", "Kotlin", "REST", "GraphQL"],
    summary:
      "I build responsive mobile experiences with thoughtful offline behavior, measurable performance, and maintainable release pipelines.",
    impact:
      "Led a cross-platform rebuild that improved startup time, crash-free sessions, and feature parity across iOS and Android.",
    degree: "BSc",
    field: "Computer Science",
  },
  {
    headline: "Application Security Engineer | Secure product delivery",
    currentTitle: "Application Security Engineer",
    priorTitle: "Security Analyst",
    years: 7,
    skills: ["Python", "AWS", "Docker", "Kubernetes", "Linux", "GitHub Actions"],
    summary:
      "I help engineers ship securely through practical threat modeling, focused automation, and fixes that fit real delivery constraints.",
    impact:
      "Built a security review program and CI controls that shortened remediation time without slowing normal product releases.",
    degree: "MSc",
    field: "Cybersecurity",
  },
  {
    headline: "Machine Learning Engineer | Production decision systems",
    currentTitle: "Machine Learning Engineer",
    priorTitle: "Data Scientist",
    years: 6,
    skills: ["Python", "Machine Learning", "PyTorch", "SQL", "AWS", "Docker"],
    summary:
      "I take models beyond notebooks, combining careful evaluation with reliable services, monitoring, and feedback loops.",
    impact:
      "Productionized a ranking model with drift monitoring and an experiment framework that made performance trade-offs visible.",
    degree: "MSc",
    field: "Machine Learning",
  },
  {
    headline: "Developer Experience Advocate | APIs, docs, community",
    currentTitle: "Developer Advocate",
    priorTitle: "Solutions Engineer",
    years: 6,
    skills: ["JavaScript", "TypeScript", "Node.js", "REST", "Content Strategy", "Customer Success"],
    summary:
      "I connect product teams with developers through precise documentation, useful examples, workshops, and a strong feedback loop.",
    impact:
      "Rebuilt the quick-start journey and created technical workshops that improved activation and surfaced actionable API feedback.",
    degree: "BA",
    field: "Technical Communication",
  },
  {
    headline: "Implementation Consultant | Healthcare integrations",
    currentTitle: "Implementation Consultant",
    priorTitle: "Customer Success Engineer",
    years: 5,
    skills: ["Customer Success", "Clinical Data", "SQL", "REST", "Data Analysis"],
    summary:
      "I guide complex customers from discovery through launch, making integrations understandable and keeping clinical stakeholders confident.",
    impact:
      "Delivered multiple concurrent enterprise implementations while improving handoffs, data validation, and post-launch adoption.",
    degree: "BSc",
    field: "Health Informatics",
  },
  {
    headline: "Fraud Risk Analyst | Payments and decisioning",
    currentTitle: "Fraud Risk Analyst",
    priorTitle: "Risk Operations Analyst",
    years: 5,
    skills: ["Fraud Detection", "SQL", "Python", "Data Analysis", "Tableau"],
    summary:
      "I balance loss prevention with customer experience using clear rules, thoughtful investigations, and monitored decision strategies.",
    impact:
      "Refined transaction controls and analyst workflows to reduce avoidable false positives while maintaining strong loss performance.",
    degree: "BSc",
    field: "Economics",
  },
  {
    headline: "Lifecycle Marketing Manager | Retention and experimentation",
    currentTitle: "Lifecycle Marketing Manager",
    priorTitle: "Growth Marketing Specialist",
    years: 6,
    skills: ["Content Strategy", "Data Analysis", "SQL", "Product Strategy", "Customer Success"],
    summary:
      "I build lifecycle programs grounded in customer behavior, clear messaging, and disciplined experimentation across channels.",
    impact:
      "Launched segmented onboarding and retention journeys that improved activation and established a repeatable testing cadence.",
    degree: "BA",
    field: "Marketing Analytics",
  },
  {
    headline: "Marketplace Operations Lead | Scalable service delivery",
    currentTitle: "Marketplace Operations Lead",
    priorTitle: "Operations Analyst",
    years: 7,
    skills: ["Data Analysis", "SQL", "Tableau", "Customer Success", "Product Strategy"],
    summary:
      "I turn messy marketplace operations into measurable systems, balancing customer experience, partner health, and efficient execution.",
    impact:
      "Redesigned service-level reporting and escalation paths, improving response consistency across a rapidly growing partner network.",
    degree: "BBA",
    field: "Operations Management",
  },
  {
    headline: "Engineering Manager | Product-minded technical leadership",
    currentTitle: "Engineering Manager",
    priorTitle: "Staff Software Engineer",
    years: 12,
    skills: ["TypeScript", "Node.js", "PostgreSQL", "AWS", "Product Strategy", "GitHub Actions"],
    summary:
      "I build healthy engineering teams that pair strong technical judgement with crisp product delivery and sustainable operating habits.",
    impact:
      "Grew and coached a multi-disciplinary team while improving planning reliability, ownership boundaries, and incident learning.",
    degree: "MEng",
    field: "Software Engineering",
  },
  {
    headline: "Clinical Data Engineer | Interoperable health platforms",
    currentTitle: "Clinical Data Engineer",
    priorTitle: "Healthcare Data Analyst",
    years: 6,
    skills: ["Clinical Data", "Python", "SQL", "PostgreSQL", "Airflow", "REST"],
    summary:
      "I build careful healthcare data pipelines with traceable transformations, strong validation, and respect for clinical context.",
    impact:
      "Delivered an interoperable ingestion pipeline that improved data quality visibility and reduced manual reconciliation for care teams.",
    degree: "MSc",
    field: "Biomedical Informatics",
  },
];

const JOBS = [
  {
    company: "northwind",
    title: "Senior Full-Stack Engineer",
    description:
      "Own customer-facing capabilities across our React and Node.js platform, shape service boundaries, and mentor engineers through design and delivery.",
    employmentType: "FULL_TIME",
    experience: [6, 11],
    location: "Remote across EMEA",
    remote: true,
    salary: [105000, 140000, "USD"],
    status: "OPEN",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS", "GraphQL"],
    applicationCount: 100,
    flagship: true,
  },
  {
    company: "northwind",
    title: "Staff Product Designer",
    description:
      "Lead discovery and interaction design for complex developer workflows while evolving an accessible, coherent product system.",
    employmentType: "FULL_TIME",
    experience: [7, 12],
    location: "London or remote in Europe",
    remote: true,
    salary: [85000, 115000, "GBP"],
    status: "OPEN",
    skills: ["Figma", "User Research", "Product Strategy", "Accessibility", "Content Strategy"],
    applicationCount: 24,
  },
  {
    company: "northwind",
    title: "Developer Experience Advocate",
    description:
      "Help developers succeed through excellent examples, technical content, workshops, and a tight feedback loop with product engineering.",
    employmentType: "FULL_TIME",
    experience: [4, 8],
    location: "Remote",
    remote: true,
    salary: [80000, 110000, "EUR"],
    status: "OPEN",
    skills: ["TypeScript", "Node.js", "REST", "Content Strategy", "Customer Success"],
    applicationCount: 15,
  },
  {
    company: "northwind",
    title: "Engineering Manager, Data Platform",
    description:
      "Coach a platform group responsible for data ingestion, reliability, and the engineering foundations used across Northwind.",
    employmentType: "FULL_TIME",
    experience: [9, 15],
    location: "London, United Kingdom",
    remote: false,
    salary: [120000, 155000, "GBP"],
    status: "CLOSED",
    skills: ["PostgreSQL", "Kafka", "AWS", "Kubernetes", "Product Strategy"],
    applicationCount: 12,
  },
  {
    company: "northwind",
    title: "Application Security Engineer",
    description:
      "Partner with product teams on threat modeling, secure defaults, and practical automation across our software delivery lifecycle.",
    employmentType: "FULL_TIME",
    experience: [5, 10],
    location: "Remote across EMEA",
    remote: true,
    salary: [95000, 130000, "EUR"],
    status: "DRAFT",
    skills: ["Python", "AWS", "Kubernetes", "Linux", "GitHub Actions"],
    applicationCount: 0,
  },
  {
    company: "cedar",
    title: "Clinical Data Engineer",
    description:
      "Build validated clinical-data pipelines and integrations that give care teams timely, traceable information without compromising privacy.",
    employmentType: "FULL_TIME",
    experience: [4, 8],
    location: "Beirut, Lebanon (hybrid)",
    remote: false,
    salary: [48000, 72000, "USD"],
    status: "OPEN",
    skills: ["Clinical Data", "Python", "SQL", "PostgreSQL", "Airflow", "REST"],
    applicationCount: 22,
  },
  {
    company: "cedar",
    title: "Healthcare Implementation Specialist",
    description:
      "Guide clinics through workflow discovery, data migration, integration testing, training, and a confident production launch.",
    employmentType: "FULL_TIME",
    experience: [3, 7],
    location: "Beirut, Lebanon",
    remote: false,
    salary: [36000, 54000, "USD"],
    status: "CLOSED",
    skills: ["Customer Success", "Clinical Data", "SQL", "REST", "Data Analysis"],
    applicationCount: 14,
  },
  {
    company: "cedar",
    title: "Product Manager, Care Coordination",
    description:
      "Define the next generation of care-coordination workflows with clinicians, implementation teams, designers, and engineers.",
    employmentType: "FULL_TIME",
    experience: [5, 9],
    location: "Remote within GMT to GMT+4",
    remote: true,
    salary: [60000, 85000, "USD"],
    status: "CLOSED",
    skills: ["Product Strategy", "User Research", "Clinical Data", "SQL"],
    applicationCount: 11,
  },
  {
    company: "cedar",
    title: "QA Automation Engineer",
    description:
      "Develop a risk-based automation strategy for clinical workflows, integrations, and the browser experiences used by care teams.",
    employmentType: "CONTRACT",
    experience: [3, 7],
    location: "Remote",
    remote: true,
    salary: [42000, 60000, "USD"],
    status: "DRAFT",
    skills: ["Playwright", "TypeScript", "REST", "GitHub Actions", "SQL"],
    applicationCount: 0,
  },
  {
    company: "atlaspay",
    title: "Senior Backend Engineer, Payments",
    description:
      "Design resilient payment services, reconciliation flows, and operational tooling for a high-volume multi-market platform.",
    employmentType: "FULL_TIME",
    experience: [6, 11],
    location: "Dubai, United Arab Emirates",
    remote: false,
    salary: [300000, 420000, "AED"],
    status: "OPEN",
    skills: ["Go", "PostgreSQL", "Redis", "Kafka", "Docker", "AWS"],
    applicationCount: 25,
  },
  {
    company: "atlaspay",
    title: "Fraud Risk Analyst",
    description:
      "Investigate payment behavior, tune decision strategies, and partner with product teams to reduce loss without harming good customers.",
    employmentType: "FULL_TIME",
    experience: [3, 7],
    location: "Dubai or remote in MENA",
    remote: true,
    salary: [180000, 250000, "AED"],
    status: "OPEN",
    skills: ["Fraud Detection", "SQL", "Python", "Data Analysis", "Tableau"],
    applicationCount: 16,
  },
  {
    company: "atlaspay",
    title: "Mobile Engineer",
    description:
      "Build secure, responsive merchant experiences across iOS and Android, from onboarding through transaction operations.",
    employmentType: "FULL_TIME",
    experience: [4, 9],
    location: "Remote within MENA and Europe",
    remote: true,
    salary: [210000, 310000, "AED"],
    status: "OPEN",
    skills: ["React Native", "TypeScript", "Swift", "Kotlin", "REST"],
    applicationCount: 13,
  },
  {
    company: "atlaspay",
    title: "Data Science Lead, Risk",
    description:
      "Lead model development and evaluation for payment-risk decisions while building strong production feedback and monitoring practices.",
    employmentType: "FULL_TIME",
    experience: [8, 14],
    location: "Dubai, United Arab Emirates",
    remote: false,
    salary: [360000, 500000, "AED"],
    status: "DRAFT",
    skills: ["Python", "Machine Learning", "PyTorch", "SQL", "Fraud Detection"],
    applicationCount: 0,
  },
  {
    company: "lumen",
    title: "Senior Frontend Engineer",
    description:
      "Build fast merchant workflows and an accessible design system for independent brands running their business on Lumen.",
    employmentType: "FULL_TIME",
    experience: [5, 10],
    location: "Toronto, Canada (hybrid)",
    remote: false,
    salary: [125000, 160000, "CAD"],
    status: "OPEN",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Accessibility", "Playwright"],
    applicationCount: 21,
  },
  {
    company: "lumen",
    title: "Marketplace Operations Manager",
    description:
      "Scale partner operations, service-level reporting, and escalation programs across Lumen's growing marketplace ecosystem.",
    employmentType: "FULL_TIME",
    experience: [5, 9],
    location: "Toronto, Canada",
    remote: false,
    salary: [90000, 120000, "CAD"],
    status: "CLOSED",
    skills: ["Data Analysis", "SQL", "Tableau", "Customer Success", "Product Strategy"],
    applicationCount: 12,
  },
  {
    company: "lumen",
    title: "Lifecycle Marketing Manager",
    description:
      "Create segmented onboarding and retention programs that help merchants find value quickly and grow with the platform.",
    employmentType: "PART_TIME",
    experience: [4, 8],
    location: "Remote within Canada",
    remote: true,
    salary: [65000, 85000, "CAD"],
    status: "DRAFT",
    skills: ["Content Strategy", "Data Analysis", "SQL", "Product Strategy"],
    applicationCount: 0,
  },
  {
    company: "greenline",
    title: "IoT Platform Engineer",
    description:
      "Build the event-driven platform that securely connects vehicles, depots, telemetry services, and fleet operations.",
    employmentType: "FULL_TIME",
    experience: [5, 10],
    location: "Berlin, Germany",
    remote: false,
    salary: [85000, 115000, "EUR"],
    status: "OPEN",
    skills: ["Go", "Kafka", "PostgreSQL", "Kubernetes", "AWS", "Terraform"],
    applicationCount: 19,
  },
  {
    company: "greenline",
    title: "Battery Analytics Scientist",
    description:
      "Develop and productionize models that explain battery health, range, and charging behavior across a connected electric fleet.",
    employmentType: "FULL_TIME",
    experience: [4, 9],
    location: "Berlin or remote within Germany",
    remote: true,
    salary: [78000, 105000, "EUR"],
    status: "OPEN",
    skills: ["Python", "Machine Learning", "PyTorch", "SQL", "Data Analysis"],
    applicationCount: 14,
  },
  {
    company: "greenline",
    title: "Technical Program Manager",
    description:
      "Coordinate vehicle, infrastructure, and software programs with clear dependencies, operational readiness, and measurable outcomes.",
    employmentType: "CONTRACT",
    experience: [7, 12],
    location: "Berlin, Germany (hybrid)",
    remote: false,
    salary: [75000, 98000, "EUR"],
    status: "CLOSED",
    skills: ["Product Strategy", "Data Analysis", "Customer Success", "User Research"],
    applicationCount: 8,
  },
  {
    company: "greenline",
    title: "Site Reliability Engineer",
    description:
      "Improve service reliability, observability, and incident learning for systems coordinating vehicles and charging infrastructure.",
    employmentType: "FULL_TIME",
    experience: [5, 10],
    location: "Remote within the European Union",
    remote: true,
    salary: [90000, 120000, "EUR"],
    status: "OPEN",
    skills: ["Kubernetes", "Terraform", "AWS", "Linux", "Docker", "GitHub Actions"],
    applicationCount: 10,
  },
];

module.exports = {
  ARCHETYPES,
  CANDIDATE_NAMES,
  COMPANIES,
  EMPLOYERS,
  INSTITUTIONS,
  JOBS,
  LOCATIONS,
  SKILLS,
};
